spring:
  application:
    name: api
  profiles:
    active: local
    include: db
  jackson:
    deserialization:
      use-big-decimal-for-floats: true
  mvc:
    async:
      request-timeout: 180000

token:
  secret:
    key: ${JWT_KEY}
  access-token:
    plus-hour: 1
  refresh-token:
    plus-hour: 12